export function sharedSchemas(): Record<string, unknown> {
  return {
    Error: {
      type: 'object',
      properties: {
        error: { type: 'string', description: 'Human-readable error message' },
      },
      required: ['error'],
    },
    ValidationError: {
      type: 'object',
      properties: {
        error: { type: 'string', example: 'Validation failed' },
        details: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              field: { type: 'string', description: 'Dot-separated field path' },
              message: { type: 'string' },
            },
          },
        },
      },
      required: ['error', 'details'],
    },
    Message: {
      type: 'object',
      properties: {
        message: { type: 'string' },
      },
      required: ['message'],
    },
    Success: {
      type: 'object',
      properties: {
        success: { type: 'boolean', enum: [true] },
      },
      required: ['success'],
    },
    Person: {
      type: 'object',
      description: 'A person (contact) in your network',
      properties: {
        id: { type: 'string', description: 'CUID identifier' },
        userId: { type: 'string', description: 'CUID identifier' },
        name: { type: 'string', description: 'First name' },
        surname: { type: ['string', 'null'] },
        middleName: { type: ['string', 'null'] },
        secondLastName: { type: ['string', 'null'] },
        nickname: { type: ['string', 'null'] },
        lastContact: { type: ['string', 'null'], format: 'date-time', description: 'Date of last contact' },
        notes: { type: ['string', 'null'], description: 'Markdown-formatted notes' },
        relationshipToUserId: { type: ['string', 'null'], description: 'ID of the relationship type to the user' },
        contactReminderEnabled: { type: 'boolean' },
        contactReminderInterval: { type: ['integer', 'null'], minimum: 1, maximum: 99 },
        contactReminderIntervalUnit: {
          oneOf: [
            { $ref: '#/components/schemas/ReminderIntervalUnit' },
            { type: 'null' },
          ],
        },
        relationshipToUser: {
          oneOf: [
            { $ref: '#/components/schemas/RelationshipTypeSummary' },
            { type: 'null' },
          ],
        },
        lastContactReminderSent: { type: ['string', 'null'], format: 'date-time' },
        cardDavSyncEnabled: { type: 'boolean' },
        prefix: { type: ['string', 'null'], description: 'Honorific prefix (Dr., Mr.)' },
        suffix: { type: ['string', 'null'], description: 'Honorific suffix (Jr., III)' },
        uid: { type: ['string', 'null'], description: 'vCard UID for CardDAV sync' },
        organization: { type: ['string', 'null'], description: 'Company / organization' },
        jobTitle: { type: ['string', 'null'], description: 'Job title' },
        photo: { type: ['string', 'null'], description: 'Photo URL or file reference' },
        gender: { type: ['string', 'null'] },
        anniversary: { type: ['string', 'null'], format: 'date-time' },
        deletedAt: { type: ['string', 'null'], format: 'date-time' },
        phoneNumbers: { type: 'array', items: { $ref: '#/components/schemas/PersonPhone' } },
        emails: { type: 'array', items: { $ref: '#/components/schemas/PersonEmail' } },
        addresses: { type: 'array', items: { $ref: '#/components/schemas/PersonAddress' } },
        urls: { type: 'array', items: { $ref: '#/components/schemas/PersonUrl' } },
        imHandles: { type: 'array', items: { $ref: '#/components/schemas/PersonIM' } },
        locations: { type: 'array', items: { $ref: '#/components/schemas/PersonLocation' } },
        customFields: { type: 'array', items: { $ref: '#/components/schemas/PersonCustomField' } },
        customFieldValues: { type: 'array', items: { $ref: '#/components/schemas/PersonCustomFieldValue' } },
        groups: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              personId: { type: 'string' },
              groupId: { type: 'string' },
              addedAt: { type: 'string', format: 'date-time' },
              group: { $ref: '#/components/schemas/Group' },
            },
          },
        },
        createdAt: { type: 'string', format: 'date-time' },
        updatedAt: { type: 'string', format: 'date-time' },
      },
      required: ['id', 'name', 'createdAt', 'updatedAt'],
    },
    CustomFieldTemplate: {
      type: 'object',
      description: 'A user-defined typed custom field template applied to people',
      properties: {
        id: { type: 'string' },
        userId: { type: 'string' },
        name: { type: 'string', example: 'Dietary restriction' },
        slug: { type: 'string', example: 'dietary-restriction', description: 'Stable, immutable, derived from name at create time' },
        type: { type: 'string', enum: ['TEXT', 'NUMBER', 'BOOLEAN', 'SELECT'] },
        options: { type: 'array', items: { type: 'string' }, description: 'Only meaningful when type=SELECT' },
        order: { type: 'integer', description: 'Display order' },
        createdAt: { type: 'string', format: 'date-time' },
        updatedAt: { type: 'string', format: 'date-time' },
        _count: {
          type: 'object',
          description: 'Aggregate counts',
          properties: {
            values: { type: 'integer', description: 'Number of people with a value for this template' },
          },
        },
      },
      required: ['id', 'userId', 'name', 'slug', 'type', 'options', 'order'],
    },
    Group: {
      type: 'object',
      description: 'A user-defined group for organizing people',
      properties: {
        id: { type: 'string', description: 'CUID identifier' },
        userId: { type: 'string', description: 'CUID identifier' },
        name: { type: 'string' },
        description: { type: ['string', 'null'] },
        color: { type: ['string', 'null'], description: 'Hex color, e.g. #FF5733' },
        deletedAt: { type: ['string', 'null'], format: 'date-time' },
        createdAt: { type: 'string', format: 'date-time' },
        updatedAt: { type: 'string', format: 'date-time' },
      },
      required: ['id', 'name', 'createdAt', 'updatedAt'],
    },
    Relationship: {
      type: 'object',
      description: 'A directional connection between two people',
      properties: {
        id: { type: 'string', description: 'CUID identifier' },
        personId: { type: 'string', description: 'CUID identifier' },
        relatedPersonId: { type: 'string', description: 'CUID identifier' },
        relationshipTypeId: { type: ['string', 'null'], description: 'CUID identifier' },
        notes: { type: ['string', 'null'] },
        person: {
          oneOf: [
            { $ref: '#/components/schemas/PersonSummary' },
            { type: 'null' },
          ],
        },
        relatedPerson: {
          oneOf: [
            { $ref: '#/components/schemas/PersonSummary' },
            { type: 'null' },
          ],
        },
        relationshipType: {
          oneOf: [
            { $ref: '#/components/schemas/RelationshipTypeSummary' },
            { type: 'null' },
          ],
        },
        deletedAt: { type: ['string', 'null'], format: 'date-time' },
        createdAt: { type: 'string', format: 'date-time' },
        updatedAt: { type: 'string', format: 'date-time' },
      },
      required: ['id', 'personId', 'relatedPersonId', 'createdAt', 'updatedAt'],
    },
    RelationshipType: {
      type: 'object',
      description: 'A custom type for categorizing relationships (e.g. Parent/Child, Friend)',
      properties: {
        id: { type: 'string', description: 'CUID identifier' },
        name: { type: 'string', description: 'Internal name (UPPER_SNAKE_CASE)' },
        label: { type: 'string', description: 'Human-readable display label' },
        color: { type: ['string', 'null'], description: 'Hex color' },
        inverseId: { type: ['string', 'null'], description: 'CUID – ID of the inverse type (e.g. Child for Parent)' },
        inverse: {
          oneOf: [
            { $ref: '#/components/schemas/RelationshipTypeSummary' },
            { type: 'null' },
          ],
        },
        deletedAt: { type: ['string', 'null'], format: 'date-time' },
        createdAt: { type: 'string', format: 'date-time' },
        updatedAt: { type: 'string', format: 'date-time' },
      },
      required: ['id', 'name', 'label', 'createdAt', 'updatedAt'],
    },
    RelationshipTypeSummary: {
      type: ['object', 'null'],
      properties: {
        id: { type: 'string', description: 'CUID identifier' },
        userId: { type: 'string', description: 'CUID identifier' },
        name: { type: 'string' },
        label: { type: 'string' },
        color: { type: ['string', 'null'] },
        inverseId: { type: ['string', 'null'] },
        createdAt: { type: 'string', format: 'date-time' },
        updatedAt: { type: 'string', format: 'date-time' },
        deletedAt: { type: ['string', 'null'], format: 'date-time' },
      },
    },
    PersonSummary: {
      type: 'object',
      properties: {
        id: { type: 'string', description: 'CUID identifier' },
        name: { type: 'string' },
        surname: { type: ['string', 'null'] },
        middleName: { type: ['string', 'null'] },
        secondLastName: { type: ['string', 'null'] },
        nickname: { type: ['string', 'null'] },
      },
      required: ['id', 'name'],
    },
    ImportantDate: {
      type: 'object',
      description: 'A significant date for a person, with optional recurring reminders',
      properties: {
        id: { type: 'string', description: 'CUID identifier' },
        personId: { type: 'string', description: 'CUID identifier' },
        title: { type: 'string', description: 'Label for this date (e.g. Birthday, Anniversary)' },
        date: { type: 'string', format: 'date-time' },
        reminderEnabled: { type: 'boolean' },
        reminderType: {
          oneOf: [
            { type: 'string', enum: ['ONCE', 'RECURRING'] },
            { type: 'null' },
          ],
        },
        reminderInterval: { type: ['integer', 'null'], minimum: 1, maximum: 99 },
        reminderIntervalUnit: {
          oneOf: [
            { $ref: '#/components/schemas/ReminderIntervalUnit' },
            { type: 'null' },
          ],
        },
        deletedAt: { type: ['string', 'null'], format: 'date-time' },
        createdAt: { type: 'string', format: 'date-time' },
        updatedAt: { type: 'string', format: 'date-time' },
      },
      required: ['id', 'personId', 'title', 'date', 'createdAt', 'updatedAt'],
    },
    UpcomingEvent: {
      type: 'object',
      description: 'An upcoming event computed from important dates and contact reminders',
      properties: {
        id: { type: 'string' },
        personId: { type: 'string', description: 'CUID identifier' },
        personName: { type: 'string' },
        type: { type: 'string', enum: ['important_date', 'contact_reminder'] },
        title: { type: ['string', 'null'] },
        titleKey: {
          oneOf: [
            { type: 'string', enum: ['timeToCatchUp'] },
            { type: 'null' },
          ],
        },
        date: { type: 'string', format: 'date-time' },
        daysUntil: { type: 'integer', description: 'Number of days until this event (negative = overdue)' },
        isYearUnknown: { type: 'boolean', description: 'Whether the original date has an unknown year (e.g. birthday without year)' },
      },
      required: ['id', 'personId', 'personName', 'type', 'title', 'titleKey', 'date', 'daysUntil', 'isYearUnknown'],
    },
    GraphNode: {
      type: 'object',
      properties: {
        id: { type: 'string' },
        label: { type: 'string' },
        groups: { type: 'array', items: { type: 'string' } },
        colors: { type: 'array', items: { type: 'string' } },
        isCenter: { type: 'boolean' },
      },
      required: ['id', 'label', 'groups', 'colors', 'isCenter'],
    },
    GraphEdge: {
      type: 'object',
      properties: {
        source: { type: 'string' },
        target: { type: 'string' },
        type: { type: 'string' },
        color: { type: 'string' },
      },
      required: ['source', 'target', 'type', 'color'],
    },
    UserProfile: {
      type: 'object',
      properties: {
        id: { type: 'string', description: 'CUID identifier' },
        email: { type: 'string', format: 'email' },
        name: { type: 'string' },
        surname: { type: ['string', 'null'] },
        nickname: { type: ['string', 'null'] },
        theme: { type: 'string', enum: ['LIGHT', 'DARK'] },
        dateFormat: { type: 'string', enum: ['MDY', 'DMY', 'YMD'] },
        language: { type: 'string', description: 'Locale code (e.g. en, es-ES, ja-JP, nb-NO, de-DE)' },
        graphMode: {
          oneOf: [
            { type: 'string', enum: ['individuals', 'bubbles'] },
            { type: 'null' },
          ],
          description: 'Null means the user has not picked a mode yet (defaults to individuals at render time)',
        },
        emailVerified: { type: 'boolean' },
        createdAt: { type: 'string', format: 'date-time' },
        updatedAt: { type: 'string', format: 'date-time' },
      },
      required: ['id', 'email', 'name', 'theme', 'dateFormat', 'language', 'createdAt', 'updatedAt'],
    },
    ReminderIntervalUnit: {
      type: 'string',
      enum: ['DAYS', 'WEEKS', 'MONTHS', 'YEARS'],
    },
    PersonPhone: {
      type: 'object',
      properties: {
        id: { type: 'string', description: 'CUID identifier' },
        personId: { type: 'string' },
        type: { type: 'string', description: 'Phone type (e.g. home, work, mobile, custom)' },
        number: { type: 'string' },
        createdAt: { type: 'string', format: 'date-time' },
      },
      required: ['id', 'personId', 'type', 'number'],
    },
    PersonEmail: {
      type: 'object',
      properties: {
        id: { type: 'string', description: 'CUID identifier' },
        personId: { type: 'string' },
        type: { type: 'string', description: 'Email type (e.g. home, work, custom)' },
        email: { type: 'string', format: 'email' },
        createdAt: { type: 'string', format: 'date-time' },
      },
      required: ['id', 'personId', 'type', 'email'],
    },
    PersonAddress: {
      type: 'object',
      properties: {
        id: { type: 'string', description: 'CUID identifier' },
        personId: { type: 'string' },
        type: { type: 'string', description: 'Address type (e.g. home, work, custom)' },
        streetLine1: { type: ['string', 'null'] },
        streetLine2: { type: ['string', 'null'] },
        locality: { type: ['string', 'null'], description: 'City' },
        region: { type: ['string', 'null'], description: 'State/Province' },
        postalCode: { type: ['string', 'null'] },
        country: { type: ['string', 'null'] },
        createdAt: { type: 'string', format: 'date-time' },
      },
      required: ['id', 'personId', 'type'],
    },
    PersonUrl: {
      type: 'object',
      properties: {
        id: { type: 'string', description: 'CUID identifier' },
        personId: { type: 'string' },
        type: { type: 'string', description: 'URL type (e.g. homepage, blog, custom)' },
        url: { type: 'string', format: 'uri' },
        createdAt: { type: 'string', format: 'date-time' },
      },
      required: ['id', 'personId', 'type', 'url'],
    },
    PersonIM: {
      type: 'object',
      properties: {
        id: { type: 'string', description: 'CUID identifier' },
        personId: { type: 'string' },
        protocol: { type: 'string', description: 'IM protocol (e.g. skype, whatsapp, telegram, signal, other)' },
        handle: { type: 'string' },
        createdAt: { type: 'string', format: 'date-time' },
      },
      required: ['id', 'personId', 'protocol', 'handle'],
    },
    PersonLocation: {
      type: 'object',
      properties: {
        id: { type: 'string', description: 'CUID identifier' },
        personId: { type: 'string' },
        type: { type: 'string', description: 'Location type (e.g. home, work, other)' },
        latitude: { type: 'number', format: 'double' },
        longitude: { type: 'number', format: 'double' },
        label: { type: ['string', 'null'], description: 'Optional label (e.g. Main Office)' },
        createdAt: { type: 'string', format: 'date-time' },
      },
      required: ['id', 'personId', 'type', 'latitude', 'longitude'],
    },
    PersonCustomField: {
      type: 'object',
      properties: {
        id: { type: 'string', description: 'CUID identifier' },
        personId: { type: 'string' },
        key: { type: 'string', description: 'Field key (e.g. X-SPOUSE)' },
        value: { type: 'string' },
        type: { type: ['string', 'null'] },
        createdAt: { type: 'string', format: 'date-time' },
      },
      required: ['id', 'personId', 'key', 'value'],
    },
    PersonCustomFieldValue: {
      type: 'object',
      description: 'A typed value for a user-defined custom field template, attached to a person',
      properties: {
        id: { type: 'string', description: 'CUID identifier' },
        personId: { type: 'string', description: 'CUID identifier' },
        templateId: { type: 'string', description: 'CUID identifier of the CustomFieldTemplate' },
        value: { type: 'string', description: 'Raw string value; semantics depend on template type' },
        template: {
          oneOf: [
            { $ref: '#/components/schemas/CustomFieldTemplate' },
            { type: 'null' },
          ],
        },
        createdAt: { type: 'string', format: 'date-time' },
        updatedAt: { type: 'string', format: 'date-time' },
      },
      required: ['id', 'personId', 'templateId', 'value', 'createdAt', 'updatedAt'],
    },
    CardDavConnection: {
      type: 'object',
      description: 'A CardDAV server connection (password excluded from responses)',
      properties: {
        id: { type: 'string', description: 'CUID identifier' },
        userId: { type: 'string' },
        serverUrl: { type: 'string', format: 'uri' },
        username: { type: 'string' },
        provider: { type: ['string', 'null'], description: 'Provider hint: google, icloud, outlook, nextcloud, custom' },
        syncEnabled: { type: 'boolean' },
        autoSyncInterval: { type: 'integer', description: 'Sync interval in seconds (60–86400)' },
        lastSyncAt: { type: ['string', 'null'], format: 'date-time' },
        autoExportNew: { type: 'boolean' },
        importMode: { type: 'string', enum: ['manual', 'notify', 'auto'] },
        lastError: { type: ['string', 'null'] },
        lastErrorAt: { type: ['string', 'null'], format: 'date-time' },
        createdAt: { type: 'string', format: 'date-time' },
        updatedAt: { type: 'string', format: 'date-time' },
      },
      required: ['id', 'userId', 'serverUrl', 'username', 'syncEnabled', 'autoExportNew', 'importMode', 'createdAt', 'updatedAt'],
    },
    JournalEntry: {
      type: 'object',
      description: 'A journal entry with optional tagged people',
      properties: {
        id: { type: 'string', description: 'CUID identifier' },
        userId: { type: 'string', description: 'User ID' },
        title: { type: 'string', description: 'Entry title' },
        date: { type: 'string', format: 'date-time', description: 'Date of the journal entry' },
        body: { type: 'string', description: 'Entry content (markdown supported)' },
        people: {
          type: 'array',
          description: 'People tagged in this entry',
          items: { $ref: '#/components/schemas/Person' },
        },
        createdAt: { type: 'string', format: 'date-time' },
        updatedAt: { type: 'string', format: 'date-time' },
        deletedAt: { type: ['string', 'null'], format: 'date-time' },
      },
      required: ['id', 'userId', 'title', 'date', 'body', 'people', 'createdAt', 'updatedAt'],
    },
  };
}
